package com.betterweather.betterweather;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.Objects;

public class MainApplication extends Application {
    @Override
    public void start(Stage stage) throws IOException {
        // Load fxml, require non-null generated by ide
        // Try not to edit this file, you will break the program
        Parent root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("weather-view.fxml")));
        Scene scene = new Scene(root, 320, 240);
        stage.setTitle("Weather Application");
        stage.setScene(scene);
        stage.show();
    }

    // Launch
    public static void main(String[] args) {
        launch();
    }
}